    lines.append("## Precision Trend")
    lines.append("")
    lines.append("```")
    lines.append("P@10")
    lines.append("100% |  100")
    lines.append(" 80% |       80   80")
    lines.append(" 60% |            60")
    lines.append(" 40% |")
    lines.append(" 20% |")
    lines.append("     +-----------------")
    lines.append("      100K  1M   10M  100M")
    lines.append("```")